name: test

on:
  - push
  - pull_request

jobs:
  build: # this name is taken as example
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest]
    #     node-version: [18.x]

    steps:
      # Cloning the repo
      - uses: actions/checkout@v2
      # Set up Node.js
      - uses: actions/setup-node@v18
      # Install dependencies
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Install npm as dependency
        run: npm install
      # Start Linter
      - name: Run linter and pytest
        run: |
          make check
