name: test

on: push

jobs:
  build: # this name is taken as example
    runs-on: ubuntu-latest

    steps:
      # Cloning the repo
      - uses: actions/checkout@v2
      # Set up Node.js
      - uses: actions/setup-node@v1
      # Install dependencies
      - run: npm install
      # Start Linter
      - run: npm run lint
      # Start tests
      # Steps can have names, it may help by debugging
      # name will be shown on Github while build
      - name: run tests
        run: npm test # name and run refer to one job, therefore a hyphen is only by name